### ISSUE TITLE
icdrama and azdrama not working

### ISSUE THREAD

**Issue by KCSOH** [cthlo/plugin.video.icdrama#3]
I keep getting "icdrama failed to resolve url" and when I get to azdrama when I click any of the episodes it just goes to a blank page.  I have tried unistall and install, even reinstalling from zip file.

**Comment by poemex** [comment]
i have the same problem but funny my old device work unlike other of my new devices

**Comment by KCSOH** [comment]
Forgot to mention that I have kodi on notebook and it has the same problem.

**Comment by dodgy3000** [comment]
I have the same problem "icdrama failed to resolve url". v1.23. mine is on an android box. The error message failed to resolve url only happens when after you select the location you want to watch the episode of the drama. any location that you select inside the episode you will get this error. example when you click on "Allupload:Full"

**Comment by KCSOH** [comment]
resolved icdrama by uninstalling add-on and repo and reinstall however azdrama is still not working.

**Comment by KCSOH** [comment]
try uninstalling add-ons and repo and reinstall from zip file. Picasaweb is
not working, I used MP4-HQ

**Comment by dodgy3000** [comment]
how to select mp4-HQ ? not all drama has this option

**Comment by KCSOH** [comment]
Sorry, I realised that now. That means to try all the others other than
picasaweb.
